services:
  app:
    restart: always
    container_name: battery-ml
    hostname: battery-ml
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    networks:
      - battery_network

networks:
  battery_network:
    external: true
    name: code_battery_network